### PR TITLE
Added Edit functionality to update an existing secret.

### PR DESCRIPTION
**Pull request by sd416**
This feature is useful where the MFA secrets are rotated periodically.

### CODE REVIEW

**Review by simnalamburt — CHANGES_REQUESTED** [review]
Hello! Thank you for contributing to the macos-totp-cli project. It appears that `totp edit <key> <secret>` is equivalent to `totp delete <key> && totp add <key> <secret>`. As a result, there is some redundancy in the code. What do you think about refactoring the common parts into a function to make the code more DRY (Don’t Repeat Yourself)?

**Comment by sd416** [comment]
@simnalamburt , I have updated the PR to update the existing secret rather than deleting and adding.

**Comment by simnalamburt** [comment]
Thanks! I'll merge this PR whenever it passes the CI

**Comment by sd416** [comment]
@simnalamburt CI failed for formatting, updated it again

**Comment by sd416** [comment]
@simnalamburt can you review it again please?

**Comment by simnalamburt** [comment]
Sorry, but I can’t merge a PR that doesn’t pass CI.

**Pull request closed without merging**
